// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: proto/voicebot.proto

package voicebot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiResponse_ResponseType int32

const (
	AiResponse_STT_RESULT  AiResponse_ResponseType = 0 // 실시간 음성인식(STT) 중간/최종 텍스트
	AiResponse_TTS_AUDIO   AiResponse_ResponseType = 1 // 봇의 대답 (16kHz PCM 오디오 스트림)
	AiResponse_END_OF_TURN AiResponse_ResponseType = 2 // 봇의 발화가 모두 끝났음을 알림
)

// Enum value maps for AiResponse_ResponseType.
var (
	AiResponse_ResponseType_name = map[int32]string{
		0: "STT_RESULT",
		1: "TTS_AUDIO",
		2: "END_OF_TURN",
	}
	AiResponse_ResponseType_value = map[string]int32{
		"STT_RESULT":  0,
		"TTS_AUDIO":   1,
		"END_OF_TURN": 2,
	}
)

func (x AiResponse_ResponseType) Enum() *AiResponse_ResponseType {
	p := new(AiResponse_ResponseType)
	*p = x
	return p
}

func (x AiResponse_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AiResponse_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_voicebot_proto_enumTypes[0].Descriptor()
}

func (AiResponse_ResponseType) Type() protoreflect.EnumType {
	return &file_proto_voicebot_proto_enumTypes[0]
}

func (x AiResponse_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AiResponse_ResponseType.Descriptor instead.
func (AiResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_voicebot_proto_rawDescGZIP(), []int{1, 0}
}

// 1. Gateway -> AI Engine (고객 발화를 전달)
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // SIP Call ID
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`     // 16kHz PCM 바이너리 (20ms)
	IsSpeaking    bool                   `protobuf:"varint,3,opt,name=is_speaking,json=isSpeaking,proto3" json:"is_speaking,omitempty"` // VAD 감지 상태 (True: 고객이 말하는 중)
	DtmfDigit     string                 `protobuf:"bytes,4,opt,name=dtmf_digit,json=dtmfDigit,proto3" json:"dtmf_digit,omitempty"`     // [IVR] DTMF 단일 문자 ('0'-'9', '*', '#'). 비어 있으면 음성 프레임
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_voicebot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voicebot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_voicebot_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetIsSpeaking() bool {
	if x != nil {
		return x.IsSpeaking
	}
	return false
}

func (x *AudioChunk) GetDtmfDigit() string {
	if x != nil {
		return x.DtmfDigit
	}
	return ""
}

// 2. AI Engine -> Gateway (STT 텍스트 결과 또는 TTS 음성을 전달)
type AiResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          AiResponse_ResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=vbgw_ai.logic.AiResponse_ResponseType" json:"type,omitempty"`
	TextContent   string                  `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`  // STT 인식 결과 또는 TTS 생성 원시 텍스트
	AudioData     []byte                  `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`        // 16kHz PCM 바이너리 (Gateway가 재생해야 할 음성)
	ClearBuffer   bool                    `protobuf:"varint,4,opt,name=clear_buffer,json=clearBuffer,proto3" json:"clear_buffer,omitempty"` // Barge-in 발생 시 기존 재생 중이던 오디오를 중단(플러시)하라는 플래그
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiResponse) Reset() {
	*x = AiResponse{}
	mi := &file_proto_voicebot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiResponse) ProtoMessage() {}

func (x *AiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voicebot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiResponse.ProtoReflect.Descriptor instead.
func (*AiResponse) Descriptor() ([]byte, []int) {
	return file_proto_voicebot_proto_rawDescGZIP(), []int{1}
}

func (x *AiResponse) GetType() AiResponse_ResponseType {
	if x != nil {
		return x.Type
	}
	return AiResponse_STT_RESULT
}

func (x *AiResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *AiResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AiResponse) GetClearBuffer() bool {
	if x != nil {
		return x.ClearBuffer
	}
	return false
}

var File_proto_voicebot_proto protoreflect.FileDescriptor

const file_proto_voicebot_proto_rawDesc = "" +
	"\n" +
	"\x14proto/voicebot.proto\x12\rvbgw_ai.logic\"\x8a\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x1f\n" +
	"\vis_speaking\x18\x03 \x01(\bR\n" +
	"isSpeaking\x12\x1d\n" +
	"\n" +
	"dtmf_digit\x18\x04 \x01(\tR\tdtmfDigit\"\xed\x01\n" +
	"\n" +
	"AiResponse\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.vbgw_ai.logic.AiResponse.ResponseTypeR\x04type\x12!\n" +
	"\ftext_content\x18\x02 \x01(\tR\vtextContent\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\x12!\n" +
	"\fclear_buffer\x18\x04 \x01(\bR\vclearBuffer\">\n" +
	"\fResponseType\x12\x0e\n" +
	"\n" +
	"STT_RESULT\x10\x00\x12\r\n" +
	"\tTTS_AUDIO\x10\x01\x12\x0f\n" +
	"\vEND_OF_TURN\x10\x022^\n" +
	"\x11VoicebotAiService\x12I\n" +
	"\rStreamSession\x12\x19.vbgw_ai.logic.AudioChunk\x1a\x19.vbgw_ai.logic.AiResponse(\x010\x01B\x1bZ\x16vbgw-ai/proto/voicebot\xf8\x01\x01b\x06proto3"

var (
	file_proto_voicebot_proto_rawDescOnce sync.Once
	file_proto_voicebot_proto_rawDescData []byte
)

func file_proto_voicebot_proto_rawDescGZIP() []byte {
	file_proto_voicebot_proto_rawDescOnce.Do(func() {
		file_proto_voicebot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_voicebot_proto_rawDesc), len(file_proto_voicebot_proto_rawDesc)))
	})
	return file_proto_voicebot_proto_rawDescData
}

var file_proto_voicebot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_voicebot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_voicebot_proto_goTypes = []any{
	(AiResponse_ResponseType)(0), // 0: vbgw_ai.logic.AiResponse.ResponseType
	(*AudioChunk)(nil),           // 1: vbgw_ai.logic.AudioChunk
	(*AiResponse)(nil),           // 2: vbgw_ai.logic.AiResponse
}
var file_proto_voicebot_proto_depIdxs = []int32{
	0, // 0: vbgw_ai.logic.AiResponse.type:type_name -> vbgw_ai.logic.AiResponse.ResponseType
	1, // 1: vbgw_ai.logic.VoicebotAiService.StreamSession:input_type -> vbgw_ai.logic.AudioChunk
	2, // 2: vbgw_ai.logic.VoicebotAiService.StreamSession:output_type -> vbgw_ai.logic.AiResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_voicebot_proto_init() }
func file_proto_voicebot_proto_init() {
	if File_proto_voicebot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_voicebot_proto_rawDesc), len(file_proto_voicebot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_voicebot_proto_goTypes,
		DependencyIndexes: file_proto_voicebot_proto_depIdxs,
		EnumInfos:         file_proto_voicebot_proto_enumTypes,
		MessageInfos:      file_proto_voicebot_proto_msgTypes,
	}.Build()
	File_proto_voicebot_proto = out.File
	file_proto_voicebot_proto_goTypes = nil
	file_proto_voicebot_proto_depIdxs = nil
}
