// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/voicebot.proto

package voicebot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoicebotAiService_StreamSession_FullMethodName = "/voicebot.ai.VoicebotAiService/StreamSession"
)

// VoicebotAiServiceClient is the client API for VoicebotAiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 통화 세션 중 AI 엔진과 실시간(Real-time)으로 통신하기 위한 양방향 스트리밍 서비스
type VoicebotAiServiceClient interface {
	StreamSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AiResponse], error)
}

type voicebotAiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoicebotAiServiceClient(cc grpc.ClientConnInterface) VoicebotAiServiceClient {
	return &voicebotAiServiceClient{cc}
}

func (c *voicebotAiServiceClient) StreamSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoicebotAiService_ServiceDesc.Streams[0], VoicebotAiService_StreamSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, AiResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoicebotAiService_StreamSessionClient = grpc.BidiStreamingClient[AudioChunk, AiResponse]

// VoicebotAiServiceServer is the server API for VoicebotAiService service.
// All implementations must embed UnimplementedVoicebotAiServiceServer
// for forward compatibility.
//
// 통화 세션 중 AI 엔진과 실시간(Real-time)으로 통신하기 위한 양방향 스트리밍 서비스
type VoicebotAiServiceServer interface {
	StreamSession(grpc.BidiStreamingServer[AudioChunk, AiResponse]) error
	mustEmbedUnimplementedVoicebotAiServiceServer()
}

// UnimplementedVoicebotAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoicebotAiServiceServer struct{}

func (UnimplementedVoicebotAiServiceServer) StreamSession(grpc.BidiStreamingServer[AudioChunk, AiResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSession not implemented")
}
func (UnimplementedVoicebotAiServiceServer) mustEmbedUnimplementedVoicebotAiServiceServer() {}
func (UnimplementedVoicebotAiServiceServer) testEmbeddedByValue()                           {}

// UnsafeVoicebotAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoicebotAiServiceServer will
// result in compilation errors.
type UnsafeVoicebotAiServiceServer interface {
	mustEmbedUnimplementedVoicebotAiServiceServer()
}

func RegisterVoicebotAiServiceServer(s grpc.ServiceRegistrar, srv VoicebotAiServiceServer) {
	// If the following call pancis, it indicates UnimplementedVoicebotAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoicebotAiService_ServiceDesc, srv)
}

func _VoicebotAiService_StreamSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoicebotAiServiceServer).StreamSession(&grpc.GenericServerStream[AudioChunk, AiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoicebotAiService_StreamSessionServer = grpc.BidiStreamingServer[AudioChunk, AiResponse]

// VoicebotAiService_ServiceDesc is the grpc.ServiceDesc for VoicebotAiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoicebotAiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voicebot.ai.VoicebotAiService",
	HandlerType: (*VoicebotAiServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSession",
			Handler:       _VoicebotAiService_StreamSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/voicebot.proto",
}
